//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 2018. 08. 28. 20:52:49
namespace QWOPNEAT
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/QWOPNEAT.wgame </summary>
        public const string GameInfo = "Content/QWOPNEAT.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Sprites
            {
                
                /// <summary> Path to Content/Assets/Sprites/background.jpg </summary>
                public const string background_jpg = "Content/Assets/Sprites/background.jpg";
                
                /// <summary> Path to Content/Assets/Sprites/background2.png </summary>
                public const string background2_png = "Content/Assets/Sprites/background2.png";
                
                /// <summary> Path to Content/Assets/Sprites/ball_test.png </summary>
                public const string ball_test_png = "Content/Assets/Sprites/ball_test.png";
                
                /// <summary> Path to Content/Assets/Sprites/finish.png </summary>
                public const string finish_png = "Content/Assets/Sprites/finish.png";
                
                /// <summary> Path to Content/Assets/Sprites/ground_bottom2.png </summary>
                public const string ground_bottom2_png = "Content/Assets/Sprites/ground_bottom2.png";
                
                /// <summary> Path to Content/Assets/Sprites/ground_top.png </summary>
                public const string ground_top_png = "Content/Assets/Sprites/ground_top.png";
                
                public sealed class Character1
                {
                    
                    /// <summary> Path to Content/Assets/Sprites/Character1/face_mask.png </summary>
                    public const string face_mask_png = "Content/Assets/Sprites/Character1/face_mask.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character1/leg_mask.png </summary>
                    public const string leg_mask_png = "Content/Assets/Sprites/Character1/leg_mask.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character1/texture.spritesheet </summary>
                    public const string texture_spritesheet = "Content/Assets/Sprites/Character1/texture.spritesheet";
                    
                    /// <summary> Texture names from spritesheet Content/Assets/Sprites/Character1/texture.spritesheet </summary>
                    public struct texture_spritesheet_TextureName
                    {
                        
                        public const string face = "face";
                        
                        public const string leg = "leg";
                    }
                }
                
                public sealed class Character2
                {
                    
                    /// <summary> Path to Content/Assets/Sprites/Character2/arm01down.png </summary>
                    public const string arm01down_png = "Content/Assets/Sprites/Character2/arm01down.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character2/arm01Up.png </summary>
                    public const string arm01Up_png = "Content/Assets/Sprites/Character2/arm01Up.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character2/arm2down.png </summary>
                    public const string arm2down_png = "Content/Assets/Sprites/Character2/arm2down.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character2/arm2up.png </summary>
                    public const string arm2up_png = "Content/Assets/Sprites/Character2/arm2up.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character2/bob.jpg </summary>
                    public const string bob_jpg = "Content/Assets/Sprites/Character2/bob.jpg";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character2/leg01down.png </summary>
                    public const string leg01down_png = "Content/Assets/Sprites/Character2/leg01down.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character2/leg02down.png </summary>
                    public const string leg02down_png = "Content/Assets/Sprites/Character2/leg02down.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character2/leg02up.png </summary>
                    public const string leg02up_png = "Content/Assets/Sprites/Character2/leg02up.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character2/leg1up.png </summary>
                    public const string leg1up_png = "Content/Assets/Sprites/Character2/leg1up.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Character2/torso.png </summary>
                    public const string torso_png = "Content/Assets/Sprites/Character2/torso.png";
                }
            }
            
            public sealed class Prefabs
            {
                
                /// <summary> Path to Content/Assets/Prefabs/Character01.wpref </summary>
                public const string Character01 = "Content/Assets/Prefabs/Character01.wpref";
                
                /// <summary> Path to Content/Assets/Prefabs/Character02.wpref </summary>
                public const string Character02 = "Content/Assets/Prefabs/Character02.wpref";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GameplayScene.wscene </summary>
            public const string GameplayScene = "Content/Scenes/GameplayScene.wscene";
        }
    }
}
