//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 2018. 08. 17. 18:11:16
namespace QWOPNEAT
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/QWOPNEAT.wgame </summary>
        public const string GameInfo = "Content/QWOPNEAT.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Sprites
            {
                
                /// <summary> Path to Content/Assets/Sprites/background.jpg </summary>
                public const string background_jpg = "Content/Assets/Sprites/background.jpg";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GameplayScene.wscene </summary>
            public const string GameplayScene = "Content/Scenes/GameplayScene.wscene";
        }
    }
}
